# numpyを用いた数値計算３

今回の目標：
- 配列同士の四則演算（要素ごとの計算）ができるようになる．
- 数学における「行列の積」,「行列のスカラー倍」を計算できるようになる．
- ベクトルの内積，ノルム，コサイン類似度を計算できるようになる．


## 今回のゴールとなる課題
あなたは映画鑑賞を趣味とする人たちをユーザーとする
マッチングアプリの開発者だとします．
できるだけ，趣味嗜好が合うユーザー同士をマッチングさせたいとします．
ユーザーには4つの映画ジャンル（アクション，恋愛，SF，コメディ）の好みを5段階で評価してもらいました．
ユーザーAと最も相性の良いユーザーは誰でしょうか？

|ジャンル| アクション|恋愛|SF|コメディ|
|---|---|---|---|---|
| user A | 5 | 1 | 4 | 2 |
| user B | 4 | 2 | 5 | 1 |
| user C | 1 | 5 | 1 | 4 |
| user D | 5 | 2 | 3 | 2 |
| user E | 2 | 4 | 1 | 5 |

まずは，いつも通りNumPyライブラリを導入しよう．

In [ ]:
import numpy as np

## 行列の演算

### 行列同士の四則演算（要素ごとの計算）
NumPy配列同士の `+`, `-`, `*`, `/` は，**「同じ位置にある要素同士」** で計算されます．

In [ ]:
A = np.array([[1, 2], 
              [3, 4]])
B = np.array([[10, 20], 
              [30, 40]])

print(A + B)  # 要素ごとの足し算
# 出力
# [[11 22]
#  [33 44]]
print(A * B)  # 要素ごとの掛け算（※行列の積ではありません！）
# 出力
# [[ 10  40]
#  [ 90 160]]

## 行列の積
線形代数で学ぶ「行と列の掛け合わせ（行列の積）」を行うには，`*` ではなく **`@` 演算子**，または **`np.dot()` 関数** を使用します．

行列 $A$ が $m \times k$ 行列、行列 $B$ が $k \times n$ 行列のとき，積$AB$が計算できて結果は $m \times n$ 行列になります．積が定義されるためには内側の次元（$k$）が一致している必要があります．

In [ ]:
# 行列の積
print(A @ B)

# 関数を使う書き方（全く同じ結果になる）
print(np.dot(A, B))

# 出力
# [[ 70 100]
#  [150 220]]
# [[ 70 100]
#  [150 220]]

## スカラー倍
行列のスカラー倍とはすべての成分に同じ数を書けることをいう．
例えば$2A$は行列$A$のすべての成分を2倍した行列を表す．
この計算は，ブロードキャストを用いて次のように書ける．

In [ ]:
print(2*A)
# 出力 
# [[2 4]
#  [6 8]]

### 行列とベクトルの積

$n$次元ベクトル$x$ (sizeが$n$のndarray) に$m\times n$の行列をかけることができる．
このとき，$x$は$n\times 1$行列と解釈される．

例えば$A x=\begin{pmatrix}1 & 2\\ 3 & 4\end{pmatrix}\begin{pmatrix}1\\2 \end{pmatrix}=\begin{pmatrix}5\\11 \end{pmatrix}$の計算は次のように書ける．

In [ ]:
x = np.array([1,2])
print(A@x)
# 出力 [ 5 11]

### 練習問題1
$3\times 3$行列$A, B$と3次元ベクトル$x$を次のように定める．
$$A=\begin{pmatrix}1&2&3\\4&5&6\\7&8&9\end{pmatrix}, \ 
B=\begin{pmatrix}9&8&7\\6&5&4\\3&2&1\end{pmatrix}, \ 
x=\begin{pmatrix}1\\2\\3\end{pmatrix}.$$

以下の計算結果を出力してください．

0. $A+B$
1. $A-B$
2. $3A$
3. $AB$
4. $BA$
5. $Ax$

<details>
<summary>解答例を見る（クリックで展開）</summary>

>```python
>A = np.arange(1,10).reshape(3,3)
>B = np.arange(9,0, -1).reshape(3,3)
>x = np.array([1,2,3])
>```
>
>0. 
>```python
>print(A+B)
># 出力 
># [[10 10 10]
>#  [10 10 10]
>#  [10 10 10]]
>```
>1. 
>```python
>print(A-B)
># 出力 
># [[-8 -6 -4]
>#  [-2  0  2]
>#  [ 4  6  8]]
>```
>2. 
>```python
>print(3*A)
># 出力
># [[ 3  6  9]
>#  [12 15 18]
>#  [21 24 27]]
>```
>2. 
>```python
>print(A@B)
># 出力
># [[ 30  24  18]
>#  [ 84  69  54]
>#  [138 114  90]]
>```
>3. 
>```python
>print(B@A)
># 出力
># [[ 90 114 138]
>#  [ 54  69  84]
>#  [ 18  24  30]]
>```
>4. 
>```python
>print(A@x)`
># 出力 [14 32 50]
>```
>
</details>

## 行列に対する操作

### 転置行列（Transpose）
転置とは，行列の「行」と「列」を入れ替える操作のこと．
行列$A$を転置した行列を$A$の**転置行列**という．
行列の積を計算する際に，形状（Shape）を合わせる目的で非常によく使われる．
`.T` という属性を用いる．

In [ ]:
C = np.array([[1, 2, 3], 
              [4, 5, 6]]) # 2行3列

# 転置して 3行2列 にする
print("元の行列:\n", C)
print("転置行列:\n", C.T)
# 出力: 
# 元の行列:
#  [[1 2 3]
#  [4 5 6]]
# 転置行列:
#  [[1 4]
#  [2 5]
#  [3 6]]

### 配列の結合（vstack, hstack）
バラバラのデータを縦や横にくっつける方法を見る．
データセットに新しい項目（列）を追加したり，新しいサンプル（行）を追加したりする実務で頻繁に使われる．

In [ ]:
P = np.array([[1, 2], [3, 4]])
Q = np.array([[5, 6], [7, 8]])
# 縦に結合 (Vertical: Pの下にQをくっつける)
# ※結合する配列はタプル () で渡します
print(np.vstack((P, Q))) # 縦にP, Qの順で結合
print(np.vstack((P, Q, P))) # 縦にP, Q, Pの順で結合

# 横に結合 (Horizontal: Pの右にくっつける)
C = np.array([[10], [20]])
print(np.hstack((A, C)))

### 練習問題2
$A, B$を練習問題1で定めた行列とする．

0. $A$の転置行列を出力してください．
1. 行列$A$の下に行列$B$をくっつけた行列を出力してください．
2. 行列$A$の右に行列$B$をくっつけた行列を出力してください．

<details>
<summary>解答例を見る（クリックで展開）</summary>

>0. 
>```python
>print(A.T)
># 出力
>#[[1 4 7]
># [2 5 8]
># [3 6 9]]
>```
>1. 
>```python
>print(np.vstack((A, B)))
># 出力
>#[[1 2 3]
># [4 5 6]
># [7 8 9]
># [9 8 7]
># [6 5 4]
># [3 2 1]]
>```
>2. 
>```python
>print(np.hstack((A, B)))
># 出力
>#[[1 2 3 9 8 7]
># [4 5 6 6 5 4]
># [7 8 9 3 2 1]]
>```
</details>

## ベクトルに対する操作 (内積とノルム)
ここからは1次元の配列（ベクトル）の計算に注目する．
AIが「この2つのデータは似ているか？」を判定するとき，
ベクトルの計算が行われる．

### ベクトルの内積
行列の積と同じ `@` を用いる．要素同士を掛けて，すべて足し合わせた「1つの数値」になる．

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("ベクトルの内積:", a @ b) 
# 出力 32 (=1*4 + 2*5 + 3*6)

### ベクトルのノルムと距離
2つのベクトルの「差」の長さを測ることで，データ間の「距離」を計算できる．
`np.linalg.norm()` を用いる．
値が小さいほど，近い点といえる．

In [ ]:
dist = np.linalg.norm(a - b) #ベクトルaとbの距離
print(np.round(dist, 2))

### コラム： `linalg` って何？
`np.linalg.norm()` という少し長いコマンドが出てきた．
`import numpy as np` を実行した時点で，この機能はすでに使えるようになっている．

*   **`linalg` の意味**: これは **Lin**ear **Alg**ebra（線形代数）の略．
*   **なぜこんな書き方をするの？**: NumPyという巨大な道具箱の中には，無数の機能が入っている．そのため，「線形代数（`linalg`）」「乱数（`random`）」「統計（`stats`）」のように，機能ごとに「引き出し（サブモジュール）」が分かれている．
*   **読み方**: `.`（ドット）は「～の」と読む．つまり `np.linalg.norm` は，**「NumPy の 線形代数引き出し の ノルム計算」**を指定していることになる．

## コサイン類似度（Cosine Similarity）
内積とノルムを組み合わせると，AI分野で最も有名な類似度指標の一つである「コサイン類似度」が計算できる．これは2つのベクトルの「なす角」を評価するもので、文章の類似度（ChatGPTの裏側など）で毎日のように使われている（$1$に近いほど似ていて、$-1$に近いほど真逆）

$$ \text{コサイン類似度}=\cos \theta = \frac{(a,b)}{ \| a\| \|b\| }$$

$(a, b)$は$a$と$b$の内積，$\theta$は$a$, $b$のなす角である．

In [ ]:
# コサイン類似度 = (aとbの内積) ÷ (aの長さ × bの長さ)
cos_sim = (a @ b) / (np.linalg.norm(a) * np.linalg.norm(b))
print("コサイン類似度:", np.round(cos_sim, 3))

### ? コラム：なぜ「距離」と「コサイン類似度」の2つを学んだの？
今回，データの似ている度合いを測る方法として，ベクトルの引き算（ユークリッド距離）と，角度を測る（コサイン類似度）の2つが登場した．これらはデータによって使い分ける．

*   **ユークリッド距離**：「数値の絶対的な大きさ」が重要なときに用いられる（例：位置情報，気温，金額）．
*   **コサイン類似度**：「大きさ」は無視して，「データの傾向（割合・パターン）」を見たいときに使われる．

### 練習問題3 
$a=(1,2,1)$, $b=(0, 1,2)$, $c=(-1,-1,0)\in \mathbb{R}^3$とする．

0. $a$と$b$のコサイン類似度を出力してください．
1. $a$と$c$のコサイン類似度を出力してください．

<details>
<summary>解答例を見る（クリックで展開）</summary>

>0. 
>```python
>a = np.array([1,2,1])
>b = np.array([0,1,2])
>c = np.array([-1,-1,0])
>cos_sim = (a @ b) / (np.linalg.norm(a) * np.linalg.norm(b))
>print(cos_sim)
># 出力
># 0.7302967433402214
>```
>1. 
>```python
>cos_sim = (a @ c) / (np.linalg.norm(a) * np.linalg.norm(c))
>print(cos_sim)
># 出力 
># -0.8660254037844387
>```
>関数定義を知っている方は，それを使うとどう書けるか考えてみましょう．
</details>

## 提出課題
冒頭の表のように，各ユーザーのジャンル別の評価が次のように与えられたとする．

In [ ]:
all_users = np.array([
    [5, 1, 4, 2], # ユーザーA 
    [4, 2, 5, 1], # ユーザーB
    [1, 5, 1, 4], # ユーザーC
    [5, 2, 3, 2], # ユーザーD
    [2, 4, 1, 5]  # ユーザーE
])

0. ユーザーAの評価ベクトル$(5,1,4,2)$のノルムを求めて出力してください．
1. 各ユーザーの評価ベクトルのノルムを順に並べた1次元配列を出力してください． 
Hint: `axis = 1`を用いる．
2. ユーザーAの評価ベクトルと各ユーザーの評価ベクトルの内積を並べた1次元配列を行列計算によって求めて出力してください． 
Hint: 行列の積を用いる．
3. ユーザーAの評価ベクトルと各ユーザーの評価ベクトルのコサイン類似度を並べた1次元配列を出力してください．
4. ユーザーAに対してコサイン類似度が（A以外で）最も高いユーザーをB, C, D, Eの中から選んでください．

### Tips 
`np.argsort()`で小さい順にインデックスを並べ替えられます．

In [ ]:
a=np.array([10,1,40,20])
print(np.argsort(a))
# 出力 [1,0,3,2]

### 発展課題
よりマッチング精度を高めるために，
さらにホラーとアニメというジャンルを追加して，ユーザーに評価値をつけてもらったところ次の表のようになりました．
|ジャンル| ホラー|アニメ|
|---|---|---|
| user A | 5 | 5 | 
| user B | 3 | 3 |
| user C | 1 | 5 |
| user D | 1 | 4 |
| user E | 2 | 4 |

このときにユーザーAとコサイン類似度の意味で最も相性のよいユーザーは誰でしょうか？