# numpyを用いた数値計算２

今回の目標：
- 2次元配列（行列）の構造を理解する
- 配列の形状（Shape）を確認・変更できるようになる
- 特定の軸（axis）に沿った統計計算（平均・合計など）を習得する

例えば次のようにテストの得点がわかっているときに
各教科，各学生の平均点や，各教科の最大得点，最小得点，などが知りたい．
4人ぐらいなら手計算できるが，90人いたら人力で計算するのは大変．
プログラムを書いて楽をしよう．

|      | 微分積分学1 | 線形代数学1 | プログラミング1 |
|---|---|---|---|
|学生A |  90 | 85 | 77 |
|学生B |  98 | 82 | 80 |
|学生C |  88 | 86 | 90 |
|学生D |  100 | 98 | 27 |


## 1次元ndarrayの復習と統計量の計算
前回，ndarrayを導入して
- 出力 print()
- ndarrayの生成，
- ndarrayの計算(ブロードキャストを含む)

を学んだ．

まずはnumpyライブラリを導入する．

In [ ]:
import numpy as np

### 例(復習)

In [ ]:
data_0 = np.array([1,2,3])
data_1 = np.arange(1,11) 
print(data_0)
print(data_1)
print(data_1 + 1)
print(data_1.sum())
# 出力  [1 2 3]
#       [ 1  2  3  4  5  6  7  8  9 10]
#       [ 2  3  4  5  6  7  8  9 10 11]
#       55

### 平均の計算

In [ ]:
print(data_1.mean())
# 出力 5.5 

注：($x_1,\cdots, x_n$の平均$)=\frac{1}{n}\sum_{k=1}^n x_k$

### 分散と標準偏差

In [ ]:
print(data_1.var()) # (標本)分散
print(data_1.std()) # 標準偏差
# 出力 
# 8.25
# 2.8722813232690143

注：$x_1, \cdots, x_n$の(標本)分散 $\sigma^2$は次で与えられる：
$$ \sigma^2= \frac{1}{n}\sum_{k=1}^n(x_k-\overline{x})^2$$

ここで，$\overline{x}$は，$x_1,\cdots, x_n$の平均を表す．

このとき$\sigma= \sqrt{\sigma^2}$を標準偏差という．

### 最大値，最小値の計算

In [ ]:
print(data_1.max())
print(data_1.min())
# 出力 10
#       1

### 練習問題
以下は2026年3月の小田原の最高気温のデータである．
このデータについて以下の問に答えてください．

16.8, 16.1, 11.7, 18.1, 16.0, 15.3, 18.7, 13.4, 13.3, 9.9, 11.0, 14.4, 10.5, 15.7, 15.1, 13.9, 14.9, 17.6, 19.9, 11.8, 14.5, 16.2, 16.6, 18.6, 12.9, 15.7, 19.0, 18.1, 20.5, 18.3, 21.8

0. データの平均を出力してください．
1. データの分散と標準偏差を出力してください．
2. データの最大値を出力してください．
3. データの最小値を出力してください．

<details>
<summary>解答例を見る（クリックで展開）</summary>

>0.
>```python
>max_temparatures = np.array([16.8, 16.1, 11.7, 18.1, 16.0, 15.3, 18.7, 13.4, 13.3, 9.9, 11.0, 14.4, 10.5, 15.7, 15.1, 13.9, 14.9, 17.6, 19.9, 11.8, 14.5, 16.2, 16.6, 18.6, 12.9, 15.7, 19.0, 18.1, 20.5, 18.3, 21.8])
>print(max_temparatures.mean())
># 出力 15.687096774193549
>```
>
>1. 
>```python
>print(max_temparatures.var())
>print(max_temparatures.std())
># 出力 8.741768990634755
>#     2.9566482696855836
>```
>
>2. 
>```python
>print(max_temparatures.max())
># 出力 21.8
>```
>3. 
>```python
>print(max_temparatures.min())
># 出力 9.9
>```
</details>

## 2次元配列の作成と計算
データは1次元配列とは限らない．
むしろ表の形で現れる2次元の配列のほうが多い．

NumPyでは，リストのリストを渡すことで簡単に2次元配列を作成できる．数学における行列と同じ構造である．
より複雑なデータを扱うためにリストのリストのリスト（3次元配列）を用いることもあるが，今回の講義では扱わない．

### ２次元配列の作成

In [ ]:
# 2行3列の行列を作成
# [ [1行目], [2行目] ] という構造になります
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
# 出力 
# [[1 2 3]
#  [4 5 6]]

### 形状（Shape）の確認
データの「形」を意識することは，多変量解析や機械学習において極めて重要である．

- `a.shape`: 行列aのサイズ（行数, 列数）をタプルで返します．
- `a.size`: 行列aの要素の総数を返します．

In [ ]:
print(a.shape)
print(a.size)
# 出力  
# (2,3)
# 6

### 形状の変換（Reshape）
要素数を変えずに，1次元から2次元，あるいはその逆へと形を整形する．

In [ ]:
b = np.arange(12)      # 0から11までの12要素（1次元）
c = b.reshape(3, 4)    # 3行4列の2次元配列に変換
print(c)
# 出力
# [[ 0  1  2  3]
#  [ 4  5  6  7]
#  [ 8  9 10 11]]

多次元配列を1次元配列にすることは平坦化(flatten)といい，次のように書く．

In [ ]:
d=c.flatten()
print(d)
print(c)
# 出力
#[ 0  1  2  3  4  5  6  7  8  9 10 11]
#[[ 0  1  2  3]
# [ 4  5  6  7]
# [ 8  9 10 11]]

上の結果を見てわかるようにcという２次元配列は，flattenによって破壊されていない．flattenは，コピーを作成して一次元配列をつくることに注意する．

### 行や列の取り出し
２次元配列が与えられたとき，特定の行や列，要素を取り出す操作(スライシング)はよく使われる．その方法を見てみよう．
numpyの2次元配列`data`が与えられたとき，
`data[(取り出す行の範囲),(取り出す列の範囲)]`と書くことで部分行列を抽出することができる．

`:`ですべての範囲を表し，`n:m`で$n$から$m-1$番目を表す．
人間の1行目, 1列目はpythonでは0行目, 0列目と数えることに注意する．

次はスライシングを理解するのに役立つシミュレーターである．

In [ ]:
import numpy as np
import ipywidgets as widgets
from IPython.display import display

# 4x4のダミーデータを作成
data = np.arange(16).reshape(4, 4)

print("【スライシング・シミュレーター】")
print("元のデータ:\n", data)
print("-" * 30)

# スライダー（プルダウン）の選択肢が変更されたときに実行される関数
def show_slicing(row, col):
    print(f"実行されるコード: data[{row}, {col}]\n")
    try:
        # 文字列として渡されたスライス指定を実際のコードとして評価
        result = eval(f"data[{row}, {col}]")
        print("抽出結果:\n", result)
    except Exception as e:
        print("エラー:", e)

# プルダウンメニューの作成
row_options = [': (すべて)', '0', '1', '2', '3', '0:2 (0行から1行)', '1:3 (1行から2行)']
col_options = [': (すべて)', '0', '1', '2', '3', '0:2 (0列から1列)', '1:3 (1列から2列)']

# コマンドの抽出（表示用の文字から実際の記号だけを切り出す）
def extract_cmd(val): return val.split()[0]

row_dropdown = widgets.Dropdown(options=[(opt, extract_cmd(opt)) for opt in row_options], value=':', description='行の指定:')
col_dropdown = widgets.Dropdown(options=[(opt, extract_cmd(opt)) for opt in col_options], value=':', description='列の指定:')

# ウィジェットの表示と関数の連携
widgets.interact(show_slicing, row=row_dropdown, col=col_dropdown);

### 練習問題
0. 1から12までの連続する整数からなる1次元配列を出力してください．
1. 0で作った1次元配列を4行3列の行列にreshapeを用いて変換して出力してください．
2. 一番下の行を取り出して出力してください．
3. 真ん中の列を取り出して出力してください．
4. 最初の行以外を取り出し，１次元配列に変換して出力してください．

<details>
<summary>解答例を見る（クリックで展開）</summary>

>0.
>```python
>one_to_twelve = np.arange(1,13)
>print(one_to_twelve)
># 出力 [ 1  2  3  4  5  6  7  8  9 10 11 12]
>```
>
>1.
>```python
>matrix = one_to_twelve.reshape(4,3)
>print(matrix)
># 出力 
># [[ 1  2  3]
>#  [ 4  5  6]
>#  [ 7  8  9]
>#  [10 11 12]]
>```
>
>2.
>```python
>print(matrix[3, : ])
># 出力 [10 11 12]
>```
>
>3.
>```python
>print(matrix[ :, 1])
># 出力 [ 2  5  8 11]
>```
>
>4. 
>```python
>print(matrix[1: , : ].flatten())
># 出力 [4 5 6 7 8 9 10 11 12]
>```

</details>

###  軸（axis）を指定した統計計算
NumPyの長所の一つは，行方向や列方向を指定して一気に集計できる点である．

- **axis=0**: 「列」ごとの計算（縦方向に集計し，行を潰す）
- **axis=1**: 「行」ごとの計算（横方向に集計し，列を潰す）


In [ ]:
data = np.array([[1, 2], [3, 4]])

print(data.mean()) # 全体の平均
print(data.mean(axis=0)) # 列ごとの平均
print(data.mean(axis=1)) # 行ごとの平均
print(data.sum(axis=1)) # 行ごとの和
# 出力
# 2.5
# [2. 3.]
# [1.5 3.5]
# [3 7]

以上はメソッドスタイルの書き方であり，次のような関数スタイルの書き方もできる．

In [ ]:
print(np.mean(data)) #全体の平均
print(np.mean(data, axis=0)) #列ごとの平均 
print(np.mean(data, axis=1)) #行ごとの平均 

---

### 提出課題
以下のテスト得点表(冒頭と同じ)についていくつかの統計量を出してみよう．
4人の学生の，3科目（微分積分学1, 線形代数学1, プログラミング1）の点数データを用いて，指示に従った計算を行ってください．
|      | 微分積分学1 | 線形代数学1 | プログラミング1 |
|---|---|---|---|
|学生A |  90 | 85 | 77 |
|学生B |  98 | 82 | 80 |
|学生C |  88 | 86 | 90 |
|学生D |  100 | 98 | 27 |

0. 表と同じように，行が学生，列が得点となるようなshape(4,3)の2次元配列を作成し，出力するプログラムを書いてください．
1. 各科目（列）ごとの平均点を出力するプログラムを書いてください．
2. 各科目（列）ごとの分散を出力するプログラムを書いてください．
3. 各学生（行）ごとの最高点を出力するプログラムを書いてください．
4. 各学生（行）ごとの最低点を出力するプログラムを書いてください．
5. 各学生（行）ごとの総得点を出力するプログラムを書いてください．
